org: '1256606127'
app: ceshi
stage: dev
component: nextjs
name: nextjs-RnCKvmIKe
inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
      - node_modules/**
    src: ./
  region: ap-chengdu
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  staticConf:
    cosConf:
      bucket: ceshi-dev-1256606127
      acl:
        permissions: public-read
      sources:
        - src: .next/static
          targetDir: /_next/static
        - src: public
          targetDir: /
  functionConf:
    eip: false
    timeout: 3
    memorySize: 128
  layers:
    - name: '${output:${stage}:${app}:ceshi-layer.name}'
      version: '${output:${stage}:${app}:ceshi-layer.version}'
